import { defineConfig, devices } from "@playwright/test";
import path from "path";

/**
 * Absolute path to the serialised Auth.js session cookie file.
 * Written once by global-setup, consumed by every authenticated test project.
 */
export const STORAGE_STATE_PATH = path.join(
  __dirname,
  "tests/e2e/.auth/user.json"
);

export default defineConfig({
  // ─── Test discovery ──────────────────────────────────────────────────────────
  testDir: "./tests/e2e",
  testMatch: "**/*.spec.ts",

  // ─── Global setup / teardown ─────────────────────────────────────────────────
  globalSetup: "./tests/e2e/global.setup.ts",

  // ─── Runner options ──────────────────────────────────────────────────────────
  // Re-run flaky tests once before marking them as failed
  retries: process.env["CI"] ? 2 : 0,
  // Parallelise across workers; keep sequential on a single CI worker if needed
  workers: process.env["CI"] ? 1 : undefined,
  fullyParallel: true,

  // ─── Reporting ───────────────────────────────────────────────────────────────
  reporter: process.env["CI"]
    ? [["github"], ["html", { outputFolder: "playwright-report", open: "never" }]]
    : [["list"], ["html", { outputFolder: "playwright-report", open: "on-failure" }]],

  // ─── Shared context defaults ─────────────────────────────────────────────────
  use: {
    baseURL: "http://localhost:3000",

    // Capture full-page screenshots on failure for debugging
    screenshot: "only-on-failure",
    // Record video on first retry so you can replay flaky failures
    video: "on-first-retry",
    // Capture a DOM snapshot on failure
    trace: "on-first-retry",

    // Grant microphone permission globally so AudioVisualizer/getUserMedia
    // never shows a permission prompt in any test context.
    permissions: ["microphone"],

    // Generous timeout for Monaco Editor worker initialisation and
    // WebAudio API bootstrap
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
  },

  // ─── Dev-server management ───────────────────────────────────────────────────
  // Playwright spins up the Next.js dev server once and tears it down when
  // all tests complete. Set USE_EXISTING_SERVER=1 to skip (useful locally
  // when you already have `pnpm dev` running).
  webServer: {
    command: "pnpm dev",
    url: "http://localhost:3000",
    reuseExistingServer: !process.env["CI"],
    timeout: 120_000,
    // Pipe Next.js logs to the Playwright reporter output
    stdout: "pipe",
    stderr: "pipe",
    env: {
      // Override AUTH_SECRET to a stable test value so JWT signatures
      // generated by globalSetup are accepted by the dev server.
      AUTH_SECRET: process.env["AUTH_SECRET"] ?? "playwright-test-secret-32-chars!!",
      // Disable telemetry inside the child process
      NEXT_TELEMETRY_DISABLED: "1",
    },
  },

  // ─── Test projects ───────────────────────────────────────────────────────────
  projects: [
    // ── 1. Auth setup (runs once, generates storageState) ─────────────────
    {
      name: "setup",
      testMatch: "**/global.setup.ts",
      use: { ...devices["Desktop Chrome"] },
    },

    // ── 2. Authenticated tests (Chromium) ─────────────────────────────────
    {
      name: "chromium-authenticated",
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_PATH,
        // Grant microphone explicitly here too (device-level override)
        permissions: ["microphone"],
        // Fake the WebAudio / MediaDevices stack via Chrome's built-in
        // virtual audio device so AudioContext constructor doesn't fail
        launchOptions: {
          args: [
            "--use-fake-ui-for-media-stream",   // auto-accept permission prompts
            "--use-fake-device-for-media-stream", // use a synthetic audio source
            "--allow-file-access-from-files",
          ],
        },
      },
      dependencies: ["setup"],
      testIgnore: "**/global.setup.ts",
    },

    // ── 3. Unauthenticated tests (Chromium) ───────────────────────────────
    // Runs flows that must NOT have a session (redirect-to-login assertions).
    {
      name: "chromium-public",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: [
            "--use-fake-ui-for-media-stream",
            "--use-fake-device-for-media-stream",
          ],
        },
      },
      testMatch: "**/public.spec.ts",
    },
  ],

  // ─── Output artefacts ────────────────────────────────────────────────────────
  outputDir: "test-results",
});
